{{- if and .Values.ingress.tls.enabled (not (lookup "v1" "Secret" .Release.Namespace "shieldops-tls")) }}
apiVersion: v1
kind: Secret
metadata:
  name: shieldops-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/tls.key" | b64enc }}
{{- end }}
