apiVersion: v1
kind: Service
metadata:
  name: shieldops-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: shieldops-ui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
